= Pont sur le futur ou préparation mentale

== Introduction

Faire mieux ce que l'on fait déjà bien, donner le meilleur de soi-même  dans une situation donnée, ou tout simplement mettre en oeuvre une nouvelle façon de faire: autant de raison de préparer son mental pour en faire un allié.


=== ...

Le pont sur le futur est une technique de stimulation qui consiste à projeter mentalement l'apprentissage d'un nouveau comportement dans la situation à venir, où le sujet souhaite la mettre concrètement en oeuvre.

=== ...

Elle fait partie de la boîte à outils de la préparation mentale, démarche utilisée par les sportifs en complément de la préparation physique, technique et tactique pour se donner tous les moyens de réussir la meilleure performance possible.

=== ...

Dans le milieu professionnel, elle permet de se préparer efficacement à faire face à des situations exigeantes, avec une plus grande confiance en soit et une meilleure réactivité face aux réactions de l'environnement. 


== Objectifs 

[%step]
* Renforcer un comportement utile, une posture efficace, une performance 
* Se mettre en situation de donner le meilleur de soi-même dans une situation à venir. 

